// Static game data: offices, staff roles, project templates, milestones.

export const OFFICES = [
  {
    id: "garage",
    name: { en: "Garage", it: "Garage" },
    tagline: { en: "Two dudes, one idea.", it: "Due amici, un'idea." },
    cost: 0,
    capacity: 2,
    bonus: { speed: 0, creativity: 0, server: 0 },
    unlocks: [],
    tier: 0,
    maintenance: 1, // per second
  },
  {
    id: "coworking",
    name: { en: "Coworking", it: "Coworking" },
    tagline: { en: "Free espresso, loud neighbors.", it: "Caffè gratis, vicini rumorosi." },
    cost: 5000,
    capacity: 5,
    bonus: { speed: 5, creativity: 10, server: 0 },
    unlocks: ["mobile"],
    tier: 1,
    maintenance: 8,
  },
  {
    id: "techhub",
    name: { en: "Tech Hub", it: "Tech Hub" },
    tagline: { en: "Standing desks & ping-pong.", it: "Scrivanie in piedi e ping-pong." },
    cost: 50000,
    capacity: 20,
    bonus: { speed: 15, creativity: 15, server: 25 },
    unlocks: ["mobile", "saas"],
    tier: 2,
    maintenance: 60,
  },
  {
    id: "silicon",
    name: { en: "Silicon Tower", it: "Silicon Tower" },
    tagline: { en: "Your own skyscraper.", it: "Il tuo grattacielo." },
    cost: 500000,
    capacity: 100,
    bonus: { speed: 30, creativity: 25, server: 50 },
    unlocks: ["mobile", "saas", "os"],
    tier: 3,
    maintenance: 500,
  },
  {
    id: "moon",
    name: { en: "Moon HQ", it: "Sede Lunare" },
    tagline: { en: "Zero-gravity ideation.", it: "Ideazione a gravità zero." },
    cost: 5000000,
    capacity: 300,
    bonus: { speed: 60, creativity: 50, server: 100 },
    unlocks: ["mobile", "saas", "os", "ai"],
    tier: 4,
    maintenance: 2500,
  },
];

export const STAFF_ROLES = [
  {
    id: "junior",
    name: { en: "Junior Dev", it: "Dev Junior" },
    cost: 200,
    salary: 2, // per second
    productivity: 1,
    creativity: 1,
    color: "junior",
  },
  {
    id: "senior",
    name: { en: "Senior Dev", it: "Dev Senior" },
    cost: 1500,
    salary: 10,
    productivity: 4,
    creativity: 3,
    color: "senior",
  },
  {
    id: "lead",
    name: { en: "Tech Lead", it: "Tech Lead" },
    cost: 12000,
    salary: 50,
    productivity: 12,
    creativity: 8,
    color: "lead",
  },
];

export const PROJECT_TEMPLATES = [
  {
    id: "hello",
    name: { en: "Hello World", it: "Hello World" },
    category: "basic",
    work: 50, // work-points needed
    baseRevenue: 2, // /s
    cost: 0,
    minOffice: 0,
  },
  {
    id: "todo",
    name: { en: "TodoList App", it: "App Lista" },
    category: "basic",
    work: 120,
    baseRevenue: 8,
    cost: 300,
    minOffice: 0,
  },
  {
    id: "mobile",
    name: { en: "Mobile Game", it: "Mobile Game" },
    category: "mobile",
    work: 600,
    baseRevenue: 40,
    cost: 2500,
    minOffice: 1,
  },
  {
    id: "saas",
    name: { en: "SaaS Platform", it: "Piattaforma SaaS" },
    category: "saas",
    work: 2500,
    baseRevenue: 200,
    cost: 15000,
    minOffice: 2,
  },
  {
    id: "os",
    name: { en: "Operating System", it: "Sistema Operativo" },
    category: "os",
    work: 18000,
    baseRevenue: 1800,
    cost: 120000,
    minOffice: 3,
  },
  {
    id: "ai",
    name: { en: "AGI Engine", it: "Motore AGI" },
    category: "ai",
    work: 120000,
    baseRevenue: 18000,
    cost: 1500000,
    minOffice: 4,
  },
];

export const MILESTONES = [
  {
    id: "first_desk",
    title: { en: "First Desk", it: "Prima Scrivania" },
    desc: { en: "Buy your first desk.", it: "Compra la tua prima scrivania." },
    reward: { gems: 5 },
    check: (s) => s.desks >= 1,
  },
  {
    id: "first_hire",
    title: { en: "First Hire", it: "Prima Assunzione" },
    desc: { en: "Hire your first developer.", it: "Assumi il primo sviluppatore." },
    reward: { gems: 5 },
    check: (s) => s.staff.length >= 1,
  },
  {
    id: "first_app",
    title: { en: "Hello World", it: "Hello World" },
    desc: { en: "Release your first app.", it: "Rilascia la prima app." },
    reward: { gems: 10 },
    check: (s) => s.releasedApps.length >= 1,
  },
  {
    id: "garage_legend",
    title: { en: "Garage Legend", it: "Garage Legend" },
    desc: { en: "Release 5 apps from the Garage.", it: "Rilascia 5 app dal Garage." },
    reward: { gems: 25, discount: 0.1 },
    check: (s) => s.garageReleases >= 5,
  },
  {
    id: "coworking",
    title: { en: "Networking", it: "Networking" },
    desc: { en: "Move into the Coworking office.", it: "Trasferisciti nel Coworking." },
    reward: { gems: 20 },
    check: (s) => s.officeTier >= 1,
  },
  {
    id: "crunch",
    title: { en: "Crunch Time", it: "Crunch Time" },
    desc: { en: "Keep devs working for 120s in-game.", it: "Dev al lavoro per 120s in-game." },
    reward: { gems: 30, productivity: 0.05 },
    check: (s) => s.crunchSeconds >= 120,
  },
  {
    id: "techhub",
    title: { en: "Tech Hub Era", it: "Era Tech Hub" },
    desc: { en: "Own the Tech Hub.", it: "Acquisisci il Tech Hub." },
    reward: { gems: 50 },
    check: (s) => s.officeTier >= 2,
  },
  {
    id: "millionaire",
    title: { en: "Millionaire", it: "Milionario" },
    desc: { en: "Earn 1M cash total.", it: "Guadagna 1M totali." },
    reward: { gems: 100 },
    check: (s) => s.totalEarned >= 1000000,
  },
  {
    id: "silicon",
    title: { en: "Silicon Tower", it: "Silicon Tower" },
    desc: { en: "Move to the Silicon Tower.", it: "Trasferisciti nella Silicon Tower." },
    reward: { gems: 200 },
    check: (s) => s.officeTier >= 3,
  },
  {
    id: "unicorn",
    title: { en: "Unicorn", it: "Unicorno" },
    desc: { en: "Reach 1B valuation.", it: "Raggiungi 1B di valutazione." },
    reward: { gems: 1000, unlock: "moon" },
    check: (s) => s.valuation >= 1000000000,
  },
];

export const EVENT_TYPES = [
  { id: "viral_trend",  effect: { hype: +25 }, duration: 30, positive: true },
  { id: "hype_spike",   effect: { hype: +35 }, duration: 20, positive: true },
  { id: "investor",     effect: { cashBonus: 2500 }, duration: 0, positive: true },
  { id: "market_crash", effect: { revenueMult: 0.5 }, duration: 120, positive: false },
  { id: "critical_bug", effect: { revenueMult: 0.7 }, duration: 60, positive: false },
  { id: "tax_audit",    effect: { cashPenalty: 0.1 }, duration: 0, positive: false },
  { id: "dev_burnout",  effect: { productivityMult: 0.6 }, duration: 90, positive: false },
];
