// Gem shop catalog — spend gems for tangible advantages.
export const GEM_ITEMS = [
  {
    id: "cash_small",
    name: { en: "Quick Cash", it: "Boost Cassa" },
    desc: { en: "Instant €500 injection.", it: "Iniezione immediata di €500." },
    cost: 5,
    type: "instant",
    apply: (s) => ({ ...s, cash: s.cash + 500 }),
  },
  {
    id: "cash_big",
    name: { en: "Seed Round", it: "Round Seed" },
    desc: { en: "Instant €10,000 boost.", it: "Boost immediato di €10,000." },
    cost: 60,
    type: "instant",
    apply: (s) => ({ ...s, cash: s.cash + 10000 }),
  },
  {
    id: "hype_boost",
    name: { en: "Viral Tweet", it: "Tweet Virale" },
    desc: { en: "Push market hype to 100%.", it: "Porta l'hype del mercato al 100%." },
    cost: 3,
    type: "instant",
    apply: (s) => ({ ...s, hype: 100 }),
  },
  {
    id: "speed_boost",
    name: { en: "Coffee Storm", it: "Uragano di Caffè" },
    desc: { en: "+100% dev productivity for 60s.", it: "+100% produttività dev per 60s." },
    cost: 10,
    type: "event",
    event: {
      id: "buff_speed",
      eventType: "gem_speed",
      title: "COFFEE STORM",
      message: "Devs are sprinting. +100% productivity.",
      positive: true,
      durationMs: 60000,
      effect: { productivityMult: 2 },
    },
  },
  {
    id: "revenue_buff",
    name: { en: "Launch Day Buzz", it: "Buzz del Launch Day" },
    desc: { en: "+50% app revenue for 90s.", it: "+50% ricavi app per 90s." },
    cost: 12,
    type: "event",
    event: {
      id: "buff_rev",
      eventType: "gem_rev",
      title: "LAUNCH DAY BUZZ",
      message: "Everyone is downloading. +50% revenue.",
      positive: true,
      durationMs: 90000,
      effect: { revenueMult: 1.5 },
    },
  },
  {
    id: "refresh_all",
    name: { en: "Mass Update", it: "Update Massivo" },
    desc: { en: "Reset obsolescence on every active app.", it: "Azzera l'obsolescenza di tutte le app." },
    cost: 25,
    type: "custom",
    apply: (s) => ({
      ...s,
      releasedApps: s.releasedApps.map((a) => ({ ...a, age: 0 })),
    }),
  },
  {
    id: "revive",
    name: { en: "Emergency Bailout", it: "Salvataggio di Emergenza" },
    desc: { en: "Revive after bankruptcy with €5,000 and full hype.", it: "Rivivi dopo la bancarotta con €5,000 e hype pieno." },
    cost: 30,
    type: "revive",
    apply: (s) => ({ ...s, cash: 5000, hype: 80, bankrupt: false }),
    onlyWhen: (s) => s.bankrupt,
  },
];
